"""Add Nano domain models for upload workflow

Revision ID: 71e6668b4da7
Revises:
Create Date: 2026-03-02 20:43:39.612909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "71e6668b4da7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Category name"),
        sa.Column("description", sa.Text(), nullable=True, comment="Category description"),
        sa.Column(
            "parent_category_id", sa.UUID(), nullable=True, comment="Parent category for hierarchy"
        ),
        sa.Column("icon_url", sa.String(length=500), nullable=True, comment="Category icon URL"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="active or inactive"),
        sa.ForeignKeyConstraint(["parent_category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_index(
        op.f("ix_categories_parent_category_id"), "categories", ["parent_category_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("job_title", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("profile_avatar", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", "DELETED", name="userstatus"),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "CREATOR", "CONSUMER", "MODERATOR", name="userrole"),
            nullable=False,
        ),
        sa.Column("preferred_language", sa.String(length=5), nullable=False),
        sa.Column("login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "accepted_terms",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when user accepted Terms of Service",
        ),
        sa.Column(
            "accepted_privacy",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when user accepted Privacy Policy",
        ),
        sa.Column(
            "deletion_requested_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when user requested account deletion",
        ),
        sa.Column(
            "deletion_scheduled_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when account will be permanently deleted",
        ),
        sa.Column(
            "deletion_reason",
            sa.Text(),
            nullable=True,
            comment="Optional user-provided reason for account deletion",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="User who performed the action (NULL for system events)",
        ),
        sa.Column(
            "action",
            sa.Enum(
                "LOGIN_SUCCESS",
                "LOGIN_FAILURE",
                "LOGOUT",
                "TOKEN_REFRESH",
                "TOKEN_BLACKLIST",
                "USER_REGISTERED",
                "USER_UPDATED",
                "USER_DELETED",
                "EMAIL_VERIFIED",
                "PASSWORD_CHANGED",
                "ACCOUNT_LOCKED",
                "ACCOUNT_UNLOCKED",
                "USER_SUSPENDED",
                "USER_UNSUSPENDED",
                "ROLE_CHANGED",
                "USER_DELETED_BY_ADMIN",
                "FAILED_SECURITY_CHECK",
                "RATE_LIMIT_HIT",
                "INVALID_TOKEN",
                "PERMISSION_DENIED",
                "DATA_CREATED",
                "DATA_MODIFIED",
                "DATA_DELETED",
                "DATA_ACCESSED",
                "CONSENT_GIVEN",
                "CONSENT_REVOKED",
                "DELETION_REQUESTED",
                "DELETION_CONFIRMED",
                name="auditaction",
            ),
            nullable=False,
            comment="Type of action performed",
        ),
        sa.Column(
            "resource_type",
            sa.String(length=50),
            nullable=True,
            comment="Type of resource affected (user, data, etc.)",
        ),
        sa.Column(
            "resource_id",
            sa.String(length=200),
            nullable=True,
            comment="ID of the resource affected",
        ),
        sa.Column(
            "event_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
            comment="Additional context about the action",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IP address from which action originated (IPv4 or IPv6)",
        ),
        sa.Column("user_agent", sa.Text(), nullable=True, comment="Browser user agent string"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when action occurred",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_resource_type"), "audit_logs", ["resource_type"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "consent_audit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="User who gave or revoked consent"),
        sa.Column(
            "consent_type",
            sa.Enum(
                "TERMS_OF_SERVICE",
                "PRIVACY_POLICY",
                "MARKETING",
                "DATA_PROCESSING",
                name="consenttype",
            ),
            nullable=False,
            comment="Type of consent",
        ),
        sa.Column(
            "accepted",
            sa.Boolean(),
            nullable=False,
            comment="True if consent was given, False if revoked",
        ),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IP address from which consent was given (IPv4 or IPv6)",
        ),
        sa.Column("user_agent", sa.Text(), nullable=True, comment="Browser user agent string"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_audit_consent_type"), "consent_audit", ["consent_type"], unique=False
    )
    op.create_index(op.f("ix_consent_audit_id"), "consent_audit", ["id"], unique=False)
    op.create_index(
        op.f("ix_consent_audit_timestamp"), "consent_audit", ["timestamp"], unique=False
    )
    op.create_index(op.f("ix_consent_audit_user_id"), "consent_audit", ["user_id"], unique=False)
    op.create_table(
        "nanos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False, comment="Creator/owner of the Nano"),
        sa.Column(
            "title", sa.String(length=200), nullable=False, comment="Nano title (max 200 chars)"
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Detailed description (max 1000 chars)"
        ),
        sa.Column(
            "duration_minutes", sa.Integer(), nullable=True, comment="Estimated duration in minutes"
        ),
        sa.Column(
            "competency_level",
            sa.Enum("BASIC", "INTERMEDIATE", "ADVANCED", name="competencylevel"),
            nullable=False,
            comment="Didactic level (1=Basic, 2=Intermediate, 3=Advanced)",
        ),
        sa.Column(
            "language", sa.String(length=5), nullable=False, comment="Content language (ISO 639-1)"
        ),
        sa.Column(
            "format",
            sa.Enum("VIDEO", "TEXT", "QUIZ", "INTERACTIVE", "MIXED", name="nanoformat"),
            nullable=False,
            comment="Content format/type",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PENDING_REVIEW", "PUBLISHED", "ARCHIVED", "DELETED", name="nanostatus"
            ),
            nullable=False,
            comment="Publishing status",
        ),
        sa.Column(
            "version", sa.String(length=20), nullable=False, comment="Semantic version (semver)"
        ),
        sa.Column(
            "thumbnail_url",
            sa.String(length=500),
            nullable=True,
            comment="Thumbnail image URL (object storage)",
        ),
        sa.Column(
            "file_storage_path",
            sa.String(length=500),
            nullable=True,
            comment="ZIP file path in object storage (MinIO)",
        ),
        sa.Column(
            "license",
            sa.Enum("CC_BY", "CC_BY_SA", "CC0", "PROPRIETARY", name="licensetype"),
            nullable=False,
            comment="Content license",
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When Nano was published",
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When Nano was archived",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "download_count", sa.Integer(), nullable=False, comment="Total downloads (cache)"
        ),
        sa.Column(
            "average_rating",
            sa.Numeric(precision=3, scale=2),
            nullable=False,
            comment="Average rating 0.00-5.00 (cache)",
        ),
        sa.Column("rating_count", sa.Integer(), nullable=False, comment="Total ratings (cache)"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nanos_average_rating"), "nanos", ["average_rating"], unique=False)
    op.create_index(op.f("ix_nanos_competency_level"), "nanos", ["competency_level"], unique=False)
    op.create_index(op.f("ix_nanos_creator_id"), "nanos", ["creator_id"], unique=False)
    op.create_index(op.f("ix_nanos_id"), "nanos", ["id"], unique=False)
    op.create_index(op.f("ix_nanos_language"), "nanos", ["language"], unique=False)
    op.create_index(op.f("ix_nanos_published_at"), "nanos", ["published_at"], unique=False)
    op.create_index(op.f("ix_nanos_status"), "nanos", ["status"], unique=False)
    op.create_table(
        "nano_category_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nano_id", sa.UUID(), nullable=False, comment="Nano reference"),
        sa.Column("category_id", sa.UUID(), nullable=False, comment="Category reference"),
        sa.Column("rank", sa.Integer(), nullable=False, comment="Display order/priority"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["nano_id"], ["nanos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nano_category_assignments_category_id"),
        "nano_category_assignments",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nano_category_assignments_id"), "nano_category_assignments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_nano_category_assignments_nano_id"),
        "nano_category_assignments",
        ["nano_id"],
        unique=False,
    )
    op.create_table(
        "nano_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nano_id", sa.UUID(), nullable=False, comment="Reference to parent Nano"),
        sa.Column(
            "version", sa.String(length=20), nullable=False, comment="Semantic version (semver)"
        ),
        sa.Column("changelog", sa.Text(), nullable=True, comment="What changed in this version"),
        sa.Column(
            "created_by_user_id", sa.UUID(), nullable=True, comment="User who created this version"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "file_storage_path",
            sa.String(length=500),
            nullable=False,
            comment="Snapshot of file path at this version",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PENDING_REVIEW", "PUBLISHED", "ARCHIVED", "DELETED", name="nanostatus"
            ),
            nullable=False,
            comment="Version status",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["nano_id"], ["nanos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nano_versions_created_at"), "nano_versions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_nano_versions_created_by_user_id"),
        "nano_versions",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_nano_versions_id"), "nano_versions", ["id"], unique=False)
    op.create_index(op.f("ix_nano_versions_nano_id"), "nano_versions", ["nano_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nano_versions_nano_id"), table_name="nano_versions")
    op.drop_index(op.f("ix_nano_versions_id"), table_name="nano_versions")
    op.drop_index(op.f("ix_nano_versions_created_by_user_id"), table_name="nano_versions")
    op.drop_index(op.f("ix_nano_versions_created_at"), table_name="nano_versions")
    op.drop_table("nano_versions")
    op.drop_index(
        op.f("ix_nano_category_assignments_nano_id"), table_name="nano_category_assignments"
    )
    op.drop_index(op.f("ix_nano_category_assignments_id"), table_name="nano_category_assignments")
    op.drop_index(
        op.f("ix_nano_category_assignments_category_id"), table_name="nano_category_assignments"
    )
    op.drop_table("nano_category_assignments")
    op.drop_index(op.f("ix_nanos_status"), table_name="nanos")
    op.drop_index(op.f("ix_nanos_published_at"), table_name="nanos")
    op.drop_index(op.f("ix_nanos_language"), table_name="nanos")
    op.drop_index(op.f("ix_nanos_id"), table_name="nanos")
    op.drop_index(op.f("ix_nanos_creator_id"), table_name="nanos")
    op.drop_index(op.f("ix_nanos_competency_level"), table_name="nanos")
    op.drop_index(op.f("ix_nanos_average_rating"), table_name="nanos")
    op.drop_table("nanos")
    op.drop_index(op.f("ix_consent_audit_user_id"), table_name="consent_audit")
    op.drop_index(op.f("ix_consent_audit_timestamp"), table_name="consent_audit")
    op.drop_index(op.f("ix_consent_audit_id"), table_name="consent_audit")
    op.drop_index(op.f("ix_consent_audit_consent_type"), table_name="consent_audit")
    op.drop_table("consent_audit")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_parent_category_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS nanostatus CASCADE")
    op.execute("DROP TYPE IF EXISTS nanoformat CASCADE")
    op.execute("DROP TYPE IF EXISTS competencylevel CASCADE")
    op.execute("DROP TYPE IF EXISTS licensetype CASCADE")
    op.execute("DROP TYPE IF EXISTS userstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS userrole CASCADE")
    op.execute("DROP TYPE IF EXISTS auditaction CASCADE")
    op.execute("DROP TYPE IF EXISTS consenttype CASCADE")
    # ### end Alembic commands ###
